### PR TITLE
Fixed failed pipeline

### LINKED ISSUE #257: Fix failed pipeline
https://github.com/pawelru/ie_status?tab=readme-ov-file

### PR DESCRIPTION
**Pull request by donyunardi**
Fixes #257

### CODE REVIEW

**Comment by donyunardi** [comment]
Schedule workflow passed:
https://github.com/insightsengineering/teal.widgets/actions/runs/10569775711

File: tests/testthat/test-plot_with_settings.R [hunk 1]
```diff
@@ -233,6 +233,10 @@ testthat::test_that("type_download_srv download all types of files and change th
 })
 
 testthat::test_that("type_download_srv downloads a png file with different dimensions", {
+  if (!require("png", quietly = TRUE)) {
+    skip("png package not available")
+  }
```
Comment (pawelru) [inline tests/testthat/test-plot_with_settings.R:238]: For this there is a dedicated testthat function - skip-if-not-installed

Comment (donyunardi) [reply tests/testthat/test-plot_with_settings.R:238]: good idea.

**Review by pawelru — APPROVED** [review]
