### PR TITLE
Fix broken `draggable_buckets`

### LINKED ISSUE #308: [Bug]: draggable_buckets doesn't update the selections
### What happened?

On the latest shiny version (1.11.1) `draggable_buckets` doesn't update the output when variables are moved:

```
library(shiny)
packageVersion("shiny")
'1.11.1'
devtools::load_all("../teal.widgets")

ui <- bslib::page_fluid(
  draggable_buckets("id", "Choices #1", c("a", "b"), c("bucket1", "bucket2")),
  verbatimTextOutput("out")
)
server <- function(input, output) {
  output$out <- renderPrint({input$id})
}
if (interactive()) shinyApp(ui, server)
```

Image

This affect many modules from TMC and TMG (and thus the teal.gallery)

### sessionInfo()

```R

```

### Relevant log output

```R

```

### Code of Conduct

- [x] I agree to follow this project's Code of Conduct.

### Contribution Guidelines

- [x] I agree to follow this project's Contribution Guidelines.

### Security Policy

- [x] I agree to follow this project's Security Policy.

### PR DESCRIPTION
**Pull request by vedhav**
Closes #308 

The subscribe callback now expects an object with the priority after this PR https://github.com/rstudio/shiny/pull/4211. So, if you update to `shiny v1.11.1` the `draggable_buckets` do not work (the init works, but since the subscribe is broken it does not update).

In the future we can think about using [`sortable`](https://rstudio.github.io/sortable/) package to replace a huge chunk of custom css/js code.

### CODE REVIEW

**Comment by llrs-roche** [comment]
Restarting the computer fixed the issues with displaying the output. Please address add tests and I'll approve the PR.

**Comment by vedhav** [comment]
Hey @llrs-roche as I mentioned in the stand-up. There is no real way to test this with our current testing toolkit. I'm thinking of implementing this in `teal.gallery`. With cypress we get more testing capabilities.
And, we were calling the callback function incorrectly in our subscribe before. That's why this change in shiny broke it. They already made sure that it is backwards compatible.

**Comment by llrs-roche** [comment]
I don't know what cypress is, it doesn't seem to be an R package. Is [this testing suit](https://docs.cypress.io/app/get-started/why-cypress) you refer to? 

If we can't test the output once the element is moved, let's test at least that the elements are movable.
With these lines the first element moved to the first bucket.

```js
const elementToMove = document.getElementById('iddraggable1'); 
const targetBucket = document.querySelector(`.bucket[data-label='bucket1']`);
targetBucket.appendChild(elementToMove);
```

To test the output we could create the widget with an element in one of the buckets. Per documentation, something like this should work:

```r

app_driver_db <- function() {
  ui <- bslib::page_fluid(
    draggable_buckets("id", "Choices #1", c("a"), c(bucket1 = "b", bucket2 = NULL))
  )

  shiny::shinyApp(ui, function(input, output) {})
}
```

Then we can test that "b" is returned as output for bucket1.

**Comment by vedhav** [comment]
I've added the tests as we spoke about. Although they only test the second half of the widget functionality. We can continue the e2e tests in `teal.gallery`.

File: tests/testthat/test-verbatim_popup_ui.R [hunk 1]
```diff
@@ -68,7 +68,7 @@ testthat::test_that(
       "Copy to Clipboard"
     )
     testthat::expect_equal(
-      app_driver$get_text(".modal-footer button:nth-of-type(2)"),
+      app_driver$get_text(".modal-footer button:nth-of-type(1)"),
```
Comment (llrs-roche) [inline tests/testthat/test-verbatim_popup_ui.R:71]: On my local machine this test fails, but I assume this is due to testing it with different branches of teal.

File: tests/testthat/test-draggable_buckets.R [hunk 2]
```diff
@@ -0,0 +1,102 @@
...
+      var element = Array.from(compBucket.querySelectorAll('.element')).find(e => e.textContent.trim() === 'A: Drug X');
+      // Move it to refBucket
+      refBucket.appendChild(element);
+      "
+    )
+    app_driver$wait_for_idle(timeout = default_idle_timeout)
+    testthat::expect_identical(
+      app_driver$get_value(input = "id"),
+      list(
+        "Ref" = list("B: Placebo", "A: Drug X"),
```
Comment (llrs-roche) [inline tests/testthat/test-draggable_buckets.R:96]: Unfortunately on my local machine the order is not the same:

```
List of 2
 $ Ref :List of 1
  ..$ : chr "B: Placebo"
 $ Comp:List of 2
  ..$ : chr "A: Drug X"
  ..$ : chr "C: Combination"
```

Could we just test that the "A: Drug X" is moved and not any other element? Testing the other elements is already tested in the previous test imho.

**Review by llrs-roche — APPROVED** [review]
Thanks for adding the tests. Approving, but please make the scope of the 4th test more limited as it fails on my local machine (Perhaps my locales affect the order).

File: tests/testthat/test-draggable_buckets.R (hunk 2 above)
Comment (llrs-roche) [reply tests/testthat/test-draggable_buckets.R:96]: Still the same error:

```
R version 4.5.1 (2025-06-13 ucrt)
Platform: x86_64-w64-mingw32/x64
Running under: Windows 11 x64 (build 22631)

Matrix products: default
  LAPACK version 3.12.1

locale:
[1] LC_COLLATE=Spanish_Spain.utf8  LC_CTYPE=Spanish_Spain.utf8   
[3] LC_MONETARY=Spanish_Spain.utf8 LC_NUMERIC=C                  
[5] LC_TIME=Spanish_Spain.utf8  
```

```
> packageVersion("bslib")
[1] '0.9.0'
> packageVersion("shiny")
[1] '1.11.1'
> packageVersion("shinytest2")
[1] '0.4.1'
```

Chrome: Version 138.0.7204.170 (Official Build) (64-bit)

Comment (llrs-roche) [reply tests/testthat/test-draggable_buckets.R]: Works well locally with the new tests!
