### PR TITLE
Fixing functional gaps in optionalSelectInput

### LINKED ISSUE #136: Rewrite documentation of optionalSelectInput
wrong Title and Description:
image

### PR DESCRIPTION
**Pull request by gogonzo**
closes #136 

- ⚠️ Fixed logic of the widget. Previously, widget initialized with single-choice-picker-input. It is also now by default, but it is conditional on `fixed_on_single`.
- Added `fixed_on_single` to toggle pickerInput to simple text when only one choice is available. 
- previously when there was `choices = NULL`, pickerInput was displayed with empty dropdown. Now when the `choices` are `NULL` simple text is displayed.
- toggle of pickerInput and text is done automatically by the js function attached to the widget, which is much more robust that `shinyjs::hidden` - previously toggle was done just on init and updateSelectInput could change the choices but wouldn't toggle properly.

### CODE REVIEW

File: R/optionalInput.R [hunk 1]
```diff
@@ -1,18 +1,18 @@
...
 #' @description `r lifecycle::badge("stable")`
-#' Hidden input widgets are useful to have the `input[[inputId]]` variable
-#' on available in the server function but no corresponding visual clutter from
-#' input widgets that provide only a single choice.
+#' Wrapper on [shinyWidgets::pickerInput()] with additional features.
+#' When `fixed = TRUE` or when the number of `choices` is less or equal to 1,
+#' the `pickerInput` widget is hidden and non-interactive widget will be displayed
+#' instead. With change of the user interface `selected` remains unchanged.
+#' Toggle of `HTML` elements is just the visual effect to avoid displaying
+#' `pickerInput` widget when there is only one choice.
```
Comment (chlebowa) [inline R/optionalInput.R:9]:
```suggestion
#' Wrapper for [shinyWidgets::pickerInput()] with additional features.
#' When `fixed = TRUE` or when the number of `choices` is less than 2,
#' the `pickerInput` widget is hidden and a non-interactive widget is displayed
#' instead. 
#' Change of the user interface does not affect the selection `selected`.
#' Toggling of `HTML` elements is just a visual effect to avoid displaying the 
#' `pickerInput` widget when there is only one choice.
```

File: R/optionalInput.R [hunk 2]
```diff
@@ -1,18 +1,18 @@
...
 #' @inheritParams shinyWidgets::pickerInput
 #' @param choices (`character`, `NULL`)\cr
-#'   If `choices` is `NULL` no `pickerInput` widget is displayed and `input[[inputId]]`
-#'   will be `""`. If `choices` is of length 1 then a label and character string will be
-#'   displayed and the `pickerInput` widget will be hidden. If the length of `choices`
-#'   is more than one the `pickerInput` element will be displayed.
-#'   If elements of the list are named then that name rather than the value
-#'   is displayed to the user.
+#' If `choices` length is less or equal to 1, the `pickerInput` widget is hidden and
+#' non-interactive widget will be displayed instead.
```
Comment (chlebowa) [inline R/optionalInput.R:14]:
```suggestion
#' If `choices` is of length 1 or less, the `pickerInput` widget is hidden and
#' a non-interactive widget is displayed instead.
```

File: R/optionalInput.R [hunk 3]
```diff
@@ -109,6 +135,7 @@ optionalSelectInput <- function(inputId, # nolint
     checkmate::check_class(label_help, "html")
   )
   checkmate::assert_flag(fixed)
+  singleton(shinyjs::useShinyjs())
```
Comment (chlebowa) [inline R/optionalInput.R:138]: is `singleton` necessary?

File: R/optionalInput.R [hunk 4]
```diff
@@ -155,26 +182,39 @@ optionalSelectInput <- function(inputId, # nolint
...
+        paste(selected, collapse = ", ")
+      } else {
+        "NULL"
+      }
+    ),
+    label_help
+  )
+
   shiny::tagList(
+    shiny::singleton(shinyjs::useShinyjs()),
```
Comment (chlebowa) [inline R/optionalInput.R:200]: prefix is redundant, I think

File: R/optionalInput.R (hunk 3 above)
Comment (gogonzo) [reply R/optionalInput.R:209]: Probably not, `shinyjs` should have it already. I'll remove `singleton` call

**Comment by gogonzo** [comment]
Example:

```r
pkgload::load_all("teal.widgets")
library(shiny)

# Create a minimal example data frame
data <- data.frame(
  AGE = c(25, 30, 40, 35, 28),
  SEX = c("Male", "Female", "Male", "Female", "Male"),
  PARAMCD = c("Val1", "Val2", "Val3", "Val4", "Val5"),
  PARAM = c("Param1", "Param2", "Param3", "Param4", "Param5"),
  AVISIT = c("Visit1", "Visit2", "Visit3", "Visit4", "Visit5"),
  stringsAsFactors = TRUE
)

ui_grid <- function(...) {
  fluidPage(
    fluidRow(
      lapply(list(...), function(x) column(4, wellPanel(x)))
    )
  )
}


app <- shinyApp(
  ui = ui_grid(
    div(
      optionalSelectInput(
        inputId = "c1",
        label = "Fixed choices",
        choices = LETTERS[1:5],
        selected = c("A", "B"),
        fixed = TRUE
      ),
      verbatimTextOutput(outputId = "c1_out")
    ),
    div(
      optionalSelectInput(
        inputId = "c2",
        label = "Single choice",
        choices = "A",
        selected = "A"
      ),
      verbatimTextOutput(outputId = "c2_out")
    ),
    div(
      optionalSelectInput(
        inputId = "c3",
        label = "NULL choices",
        choices = NULL
      ),
      verbatimTextOutput(outputId = "c3_out")
    ),
    div(
      optionalSelectInput(
        inputId = "c4",
        label = "Default",
        choices = LETTERS[1:5],
        selected = "A"
      ),
      verbatimTextOutput(outputId = "c4_out")
    ),
    div(
      optionalSelectInput(
        inputId = "c5",
        label = "Named vector",
        choices = c(`A - value A` = "A", `B - value B` = "B", `C - value C` = "C"),
        selected = "A"
      ),
      verbatimTextOutput(outputId = "c5_out")
    ),
    div(
      optionalSelectInput(
        inputId = "c6",
        label = "Variable choices",
        choices = teal.transform::variable_choices(data = data, subset = c("AGE", "SEX", "PARAMCD")),
        selected = "PARAMCD"
      ),
      verbatimTextOutput(outputId = "c6_out")
    ),
    div(
      optionalSelectInput(
        inputId = "c7",
        label = "Value choices",
        choices = teal.transform::value_choices(
          data = data,
          var_choices = c("PARAMCD", "AVISIT"),
          var_label = c("PARAM", "AVISIT")
        ),
        selected = "Val1 - Visit1"
      ),
      verbatimTextOutput(outputId = "c7_out")
    ),
    div(
      selectInput(inputId = "c8_choices", label = "Update choices", choices = letters, multiple = TRUE),
      optionalSelectInput(
        inputId = "c8",
        label = "Updated choices",
        choices = NULL,
        multiple = TRUE,
        fixed_on_single = TRUE
      ),
      verbatimTextOutput(outputId = "c8_out")
    )
  ),
  server = function(input, output, session) {
    observeEvent(input$c8_choices, ignoreNULL = FALSE, {
      updateOptionalSelectInput(
        session = session,
        inputId = "c8",
        choices = input$c8_choices,
        selected = input$c8_choices
      )
    })

    output$c1_out <- renderPrint({
      input$c1
    })
    output$c2_out <- renderPrint({
      input$c2
    })
    output$c3_out <- renderPrint({
      input$c3
    })
    output$c4_out <- renderPrint({
      input$c4
    })
    output$c5_out <- renderPrint({
      input$c5
    })
    output$c6_out <- renderPrint({
      input$c6
    })
    output$c7_out <- renderPrint({
      input$c7
    })
    output$c8_out <- renderPrint({
      input$c8
    })
  }
)

if (interactive()) {
  runApp(app)
}
```

File: R/optionalInput.R [hunk 5]
```diff
@@ -101,14 +173,15 @@ optionalSelectInput <- function(inputId, # nolint
...
   checkmate::assert_flag(multiple)
   checkmate::assert_string(sep, null.ok = TRUE)
-  stopifnot(is.list(options))
+  checkmate::assert_list(options)
   checkmate::assert(
     checkmate::check_string(label_help, null.ok = TRUE),
     checkmate::check_class(label_help, "shiny.tag"),
     checkmate::check_class(label_help, "shiny.tag.list"),
     checkmate::check_class(label_help, "html")
   )
```
Comment (kartikeyakirar) [inline R/optionalInput.R:182]: we could create a helper class `called check_char_html `that checks for HTML characters and use it to validate `label` and `label_help ` .
```
check_char_html <- function(val) {
  checkmate::assert(
    checkmate::check_string(val, null.ok = TRUE),
    checkmate::check_multi_class(val, c("shiny.tag", "shiny.tag.list", "html"))
}
```

and 
```
check_char_html(label)
check_char_html(label_help)
```

Comment (gogonzo) [reply R/optionalInput.R:182]: I wish to do this but this function probably needs some `deparse(val)` so the `checkmate::assert` throws meaningful message (see `.var.name` in the arguments). I'd prefer to postpone such decisions for later (after release)

Comment (chlebowa) [reply R/optionalInput.R:182]: Why not just run 
```
  checkmate::assert(
    checkmate::check_string(val, null.ok = TRUE),
    checkmate::check_multi_class(val, c("shiny.tag", "shiny.tag.list", "html")
  )
```

File: R/optionalInput.R [hunk 6]
```diff
@@ -137,58 +210,94 @@ optionalSelectInput <- function(inputId, # nolint
...
+    id = paste0(inputId, "_fixed"),
+    # visibility feature marked with display: none/block instead of shinyjs::hide/show
+    #  as mechanism to hide/show is handled by javascript code
+    style = if (fixed) "display: block;" else "display: none;",
+    tags$label(class = "control-label", sub(":[[:space:]]+$", "", label)),
+    # selected values as verbatim text
+    tags$code(
+      id = paste0(inputId, "_selected_text"),
+      if (length(selected) > 0) {
+        paste(selected, collapse = ", ")
```
Comment (chlebowa) [inline R/optionalInput.R:249]: `toString`?

**Comment by gogonzo** [comment]
> I think I still get the old behaviors 🤔 image
> 
> image

Yes, please add in the example `fixed_on_single = TRUE`. I keep default as `FALSE` to not make any braking changes (even if I have a gut feeling that default should be different)

File: R/optionalInput.R [hunk 7]
```diff
@@ -137,58 +210,94 @@ optionalSelectInput <- function(inputId, # nolint
...
-            )
-          },
-          label_help
-        )
+  ui_fixed <- tags$div(
+    id = paste0(inputId, "_fixed"),
+    # visibility feature marked with display: none/block instead of shinyjs::hide/show
+    #  as mechanism to hide/show is handled by javascript code
+    style = if (fixed) "display: block;" else "display: none;",
+    tags$label(class = "control-label", sub(":[[:space:]]+$", "", label)),
```
Comment (chlebowa) [inline R/optionalInput.R:244]: Is the `sub` for trimming white space? 
```
label <- "Fixed choices   "
sub(":[[:space:]]+$", "", label)
[1] "Fixed choices   "
```
How about `trimws`?

Comment (gogonzo) [reply R/optionalInput.R:244]: trimws won't work - above removes white space and preceding `:`

Comment (chlebowa) [reply R/optionalInput.R:244]: I don't think it does, actually:
```
label <- "Fixed choices  :    "
sub(":[[:space:]]+$", "", label)
[1] "Fixed choices  "
```

The trailing ones are removed but the preceding ones remain.
How about `"\\s+:\\s+$"`?

Comment (gogonzo) [reply R/optionalInput.R:244]: I don't think it is a good idea to have this gsub at all. Why do we fix a label? It's unintuitive behaviour. Do you mind if I remove this?

Comment (chlebowa) [reply R/optionalInput.R:244]: I certainly don't :slightly_smiling_face:

File: R/optionalInput.R [hunk 8]
```diff
@@ -1,18 +1,13 @@
-#' Hide, Show Label only or display a `pickerInput`
+#' Wrapper for `pickerInput`
 #'
 #' @description `r lifecycle::badge("stable")`
-#' Hidden input widgets are useful to have the `input[[inputId]]` variable
-#' on available in the server function but no corresponding visual clutter from
-#' input widgets that provide only a single choice.
+#' Wrapper for [shinyWidgets::pickerInput()] with additional features.
```
Comment (chlebowa) [inline R/optionalInput.R:4]: backticks?
```suggestion
#' Wrapper for [`shinyWidgets::pickerInput()`] with additional features.
```

File: R/optionalInput.R [hunk 9]
```diff
@@ -24,27 +19,17 @@
 #' @param fixed (`logical(1)` optional)\cr
 #'  whether to block user to select choices.
```
Comment (chlebowa) [inline R/optionalInput.R:20]:
```suggestion
#'  Specifies whether to prevent the user from selecting choices.
```

File: R/optionalInput.R [hunk 10]
```diff
@@ -24,27 +19,17 @@
...
 #'
+#' @param fixed_on_single (`logical(1)` optional)\cr
+#'  whether to block user to select a choice when there is only one or less choice.
+#'  When `FALSE`, user is still able to select or deselect the choice.
```
Comment (chlebowa) [inline R/optionalInput.R:24]:
```suggestion
#'  Specifies whether to prevent the user from selecting choices when there is only one or less choice.
#'  When `FALSE`, the user is still able to select or deselect the choice.
```

File: R/optionalInput.R [hunk 11]
```diff
@@ -137,58 +210,94 @@ optionalSelectInput <- function(inputId, # nolint
...
+      multiple = TRUE,
+      width = width,
+      options = options,
+      choicesOpt = picker_options(choices)
+    )
   )
 
   if (!is.null(label_help)) {
-    ui[[3]] <- append(ui[[3]], list(div(class = "label-help", label_help)), after = 1)
+    ui_picker[[3]] <- append(ui_picker[[3]], list(div(class = "label-help", label_help)), after = 1)
```
Comment (chlebowa) [inline R/optionalInput.R:236]:
```suggestion
    ui_picker[[3]] <- append(ui_picker[[3]], list(tags$div(class = "label-help", label_help)), after = 1)
```

File: R/optionalInput.R [hunk 12]
```diff
@@ -137,58 +210,94 @@ optionalSelectInput <- function(inputId, # nolint
...
+              $('#%1$s_input').show();
+              $('#%1$s_fixed').hide();
+            }
+          })
+        })",
+        inputId
+      )
+      tags$script(js)
+    },
+    div(ui_picker, ui_fixed)
```
Comment (chlebowa) [inline R/optionalInput.R:294]:
```suggestion
    tags$div(ui_picker, ui_fixed)
```

File: R/optionalInput.R
Comment (chlebowa) [inline R/optionalInput.R:1]: It seems we call all tags with `tags$...` so we should do the same with `div`.

**Review by chlebowa — APPROVED** [review]
:+1:
