### PR TITLE
Set minimal shiny version for a snapshots

### LINKED ISSUE #341: [Bug]:Snapshot failures found during R CMD Check
### What happened?

Hello, We've been running `R CMD check` for packages for our package registry manager PRISM ([Home | PRISM](https://prism.dev.a2-ai.cloud/)) and noticed that `teal.widgets` is failing during tests. We found the root cause to be newer versions of `shiny`, as the snapshot test passes when using `shiny 1.11.0` an older version.
The full error output:
```
checking tests Running testthat.R
  Running the tests in tests/testthat.R failed.
  Last 13 lines of output:
    + <button class="btn btn-default action-button teal-widgets-busy-disable button"
    +   id="STH-button" type="button">
    +   <span class="action-label">STH2</span>
    + </button>
    Snapshots
    To review and process snapshots locally:
    * Locate check directory.
    * Copy 'tests/testthat/_snaps' to local package.
    * Run `testthat::snapshot_accept()` to accept all changes.
    * Run `testthat::snapshot_review()` to review all changes.
    [ FAIL 1 | WARN 0 | SKIP 27 | PASS 253 ]
    Error: ! Test failures.
    Execution halted
```
Here is the failing test:
```
rtestthat::test_that("snapshot test for verbatim_popup_ui", {
  testthat::skip_if_not_installed("withr")
  withr::local_seed(1)
  testthat::expect_snapshot(verbatim_popup_ui("STH", "STH2"))
})
```
Expected Snapshot:
```
html<button class="btn btn-default action-button teal-widgets-busy-disable button"
  id="STH-button" type="button">STH2</button>
```
Snapshot when tested:
```
html<button class="btn btn-default action-button teal-widgets-busy-disable button"
  id="STH-button" type="button">
  <span class="action-label">STH2</span>
</button>
```
Happy to provide any more details or clarity if needed.

### sessionInfo()

```R

```

### Relevant log output

```R

```

### Code of Conduct

- [x] I agree to follow this project's Code of Conduct.

### Contribution Guidelines

- [x] I agree to follow this project's Contribution Guidelines.

### Security Policy

- [x] I agree to follow this project's Security Policy.

### PR DESCRIPTION
**Pull request by llrs-roche**
# Pull Request

Fixes #341

- Sets minimal shiny version for a snapshot test as it seems shiny version affects snapshots
- In interactive testing I saw some warning related to `modal_content`, the second commit on `R/verbatim_popup.R` is to remove them and simplify a bit the code

### CODE REVIEW

**Comment by donyunardi** [comment]
I never like snapshot test. Should we take this opportunity to change this test to something else? Maybe just regex if the html expression exist?

File: R/verbatim_popup.R [hunk 1]
```diff
@@ -121,7 +120,7 @@ button_click_observer <- function(click_event,
   shiny::observeEvent(
     click_event(),
     handlerExpr = {
-      req(modal_content())
+      mc <- req(modal_content())
```
Comment (osenan) [inline R/verbatim_popup.R]: I think the abbreviation here can be confusing. I would call this variable:


```suggestion
      req_mc <- req(modal_content())
```
So we know is the output of a req

File: R/verbatim_popup.R [hunk 2]
```diff
@@ -136,7 +135,7 @@ button_click_observer <- function(click_event,
                   onclick = paste0("copyToClipboard('", copied_area_id, "')")
                 )
               ),
-              tags$pre(id = copied_area_id, modal_content()),
+              tags$pre(id = copied_area_id, mc),
```
Comment (osenan) [inline R/verbatim_popup.R]:
```suggestion
              tags$pre(id = copied_area_id, req_mc),
```

File: R/verbatim_popup.R (hunk 1 above)
Comment (llrs-roche) [reply R/verbatim_popup.R]: What is the difference? The output of a req is always the first object if it is "truthy". 
To avoid confusions we could use the full name `modal_content`.

Comment (osenan) [reply R/verbatim_popup.R]: it is better, I think
